name: Bump version
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Bump version file
      uses: ./.github/actions/bump-version
    - name: Commit and push
      run: |
        git config --local user.email "auto-bump-version@github-actions.com"
        git config --local user.name "Auto Bump Version Action"
        git add .
        git commit -m "[ABV] Bump version"
        git push
